### ISSUE TITLE
Improving the UI of the website

### ISSUE THREAD

**Issue by sumitkr2000** [Anupkjha2601/food-recipes-website#24] opened 2023-05-20 06:28 UTC
Hey, @Anupkjha2601 I want to improve the UI of your website. Please assign me this issue so that I can start working on it. Thank you!

**Comment by ch-sohan** [comment] 2023-05-20 10:55
[image](https://github.com/Anupkjha2601/finalproj/assets/108716877/3cef5e19-d31f-41c6-950a-0e5a352e4301)
Hi @Anupkjha2601 I would like to work on this issue. Kindly assign this to me under GSSoc23.

**Comment by sumitkr2000** [comment] 2023-05-20 12:57
@ch-sohan i have raised this issue and will work on it. If you want to contribute please raise another issue. Thank you.

**Comment by adityavpawar** [comment] 2023-05-20 14:11
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by sumitkr2000** [comment] 2023-05-20 14:23
@adityavpawar i have raised this issue and will work on it. If you want to contribute please raise another issue. Thank you.

**Comment by shramanpaul** [comment] 2023-05-20 15:17
I would like to work on this issue under GSSOC'23. I would appreciate if the issue is assigned to me.

**Comment by pjyoti121** [comment] 2023-05-26 14:15
please assign me this project

**Closed** 2023-07-18 08:06 UTC
Labels: gssoc23
